### ISSUE TITLE
Intermittent write errors with some JSON-RPC websocket connections

### ISSUE THREAD

**Issue by cg-polygon** [0xPolygonHermez/zkevm-node#1965]
## Problem
Some RPC servers are getting this error intermittently:
``` 
panic: concurrent write to websocket connection
```
I can't reproduce this error on a different server, so must depend on a series of calls in a production env.

## Error Message
Here's an example of this error in the context of a RPC server's logs:

```
{"level":"debug","ts":1680105872.0163016,"caller":"jsonrpc/handler.go:90","msg":"Current open connections 0","pid":1,"version":"","method":"eth_chainId","requestId":44}
{"level":"debug","ts":1680105872.075237,"caller":"jsonrpc/handler.go:92","msg":"Current open connections 1","pid":1,"version":"","method":"eth_unsubscribe","requestId":21}
{"level":"debug","ts":1680105872.0752776,"caller":"jsonrpc/handler.go:93","msg":"request params [\"0x5e08372a6b2b40cdb5d99d5c93949ed4\"]","pid":1,"version":"","method":"eth_unsubscribe","requestId":21}
{"level":"debug","ts":1680105872.0753193,"caller":"jsonrpc/handler.go:90","msg":"Current open connections 0","pid":1,"version":"","method":"eth_unsubscribe","requestId":21}
{"level":"debug","ts":1680105872.0753312,"caller":"jsonrpc/handler.go:92","msg":"Current open connections 1","pid":1,"version":"","method":"eth_unsubscribe","requestId":20}
{"level":"debug","ts":1680105872.075357,"caller":"jsonrpc/handler.go:93","msg":"request params [\"0xf28fd8d98c4b49a5adfbec7daf9e1f8d\"]","pid":1,"version":"","method":"eth_unsubscribe","requestId":20}
{"level":"debug","ts":1680105872.0753856,"caller":"jsonrpc/handler.go:90","msg":"Current open connections 0","pid":1,"version":"","method":"eth_unsubscribe","requestId":20}
panic: concurrent write to websocket connection

goroutine 233 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000d13f28, 0x1, {0xc000796327?, 0xc0003d7b38?, 0x3?})
	/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:617 +0x52b
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0008469a0, 0xc0002e6800?, {0xc000796300, 0x27, 0x30})
	/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:770 +0x139
github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleWs.func3()
	/src/jsonrpc/server.go:380 +0x157
created by github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleWs
	/src/jsonrpc/server.go:374 +0x2d3
```

## Potential Issue
It looks like that write errors are not uncommon when using the Gorilla websocket library. Here's the result of ["panic: concurrent write to websocket connection"](https://github.com/gorilla/websocket/issues?q=panic%3A+concurrent+write+to+websocket+connection) on their Github Issues page.

**Comment by pc-quiknode** [comment]
getting same issue

**Comment by agnusmor** [comment]
Hi, this error has been fixed in version 0.1.3 of the node:

https://github.com/0xPolygonHermez/zkevm-node/pull/2173
https://github.com/0xPolygonHermez/zkevm-node/issues/2124

This version will be deployed on testnet/mainnet in the next days (we are still testing it)

**Comment by sjoshi10** [comment]
We are still seeing this issue with latest version of zkevm-node. 

```
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]: 2023-07-26T15:57:01.061Z        INFO        state/l2block.go:104        new l2 blocks detected, Number 1827675, Hash 0x710cb1876beabbc964041e64fe>
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]: panic: concurrent write to websocket connection
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]: goroutine 96417 [running]:
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]: github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000ecfee0, 0x1, {0xc000ec2400?, 0xc0009ac5c8?, 0x3?})
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]:         /home/ansible-10000/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:617 +0x50b
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]: github.com/gorilla/websocket.(*Conn).WriteMessage(0xc00108c2c0, 0xc000fd5600?, {0xc000ec2000, 0x7d7, 0x800})
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]:         /home/ansible-10000/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:770 +0x139
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]: github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleWs.func3()
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]:         /tmp/zkevmnode-0.2.0/jsonrpc/server.go:374 +0x21f
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]: created by github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleWs
Jul 26 15:57:01 zkevm-vm zkevm-node[7786]:         /tmp/zkevmnode-0.2.0/jsonrpc/server.go:366 +0x305
Jul 26 15:57:01 zkevm-vm systemd[1]: zkrpc.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 26 15:57:01 zkevm-vm systemd[1]: zkrpc.service: Failed with result 'exit-code'.
Jul 26 15:57:01 zkevm-vm systemd[1]: zkrpc.service: Consumed 1min 39.564s CPU time.
Jul 26 15:57:06 zkevm-vm systemd[1]: zkrpc.service: Scheduled restart job, restart counter is at 2.
Jul 26 15:57:06 zkevm-vm systemd[1]: Stopped ZKEVM RPC.
Jul 26 15:57:06 zkevm-vm systemd[1]: zkrpc.service: Consumed 1min 39.564s CPU time.
Jul 26 15:57:06 zkevm-vm systemd[1]: Started ZKEVM RPC.
Jul 26 15:57:06 zkevm-vm zkevm-node[32320]: Version:      v0.2.0
Jul 26 15:57:06 zkevm-vm zkevm-node[32320]: Git revision: 6fd4c75
```
