### ISSUE TITLE
Doesn't work with L1 RPC Geth

### ISSUE THREAD

**Issue by sjoshi10** [0xPolygonHermez/zkevm-node#2000]
#### System information

zkEVM Node version: `v0.0.3-RC36`
OS & Version: Ubuntu 22.04.1 LTS
Network: Mainnet

#### Steps to reproduce the behaviour

I've tried using multiple Geth archive nodes as L1 RPC but they all crash with the following errors. Nethermind and Erigon works fine without any issues. 

#### Logs

````
Apr 06 20:13:28  zkevm-node[30287]: 2023-04-06T20:13:28.564Z        FATAL        cmd/run.go:98        error getting forks: request timed out
Apr 06 20:13:28  zkevm-node[30287]: /tmp/zkevmnode-0.0.3-RC36/log/log.go:140 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
Apr 06 20:13:28  zkevm-node[30287]: /tmp/zkevmnode-0.0.3-RC36/log/log.go:221 github.com/0xPolygonHermez/zkevm-node/log.Fatal()
Apr 06 20:13:28  zkevm-node[30287]: /tmp/zkevmnode-0.0.3-RC36/cmd/run.go:98 main.start()
Apr 06 20:13:28  zkevm-node[30287]: /home/ansible-10000/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274 github.com/urfave/cli/v2.(*Command).Run()
Apr 06 20:13:28  zkevm-node[30287]: /home/ansible-10000/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:267 github.com/urfave/cli/v2.(*Command).Run()
Apr 06 20:13:28  zkevm-node[30287]: /home/ansible-10000/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332 github.com/urfave/cli/v2.(*App).RunContext()
Apr 06 20:13:28  zkevm-node[30287]: /home/ansible-10000/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309 github.com/urfave/cli/v2.(*App).Run()
Apr 06 20:13:28  zkevm-node[30287]: /tmp/zkevmnode-0.0.3-RC36/cmd/main.go:140 main.main()
Apr 06 20:13:28  zkevm-node[30287]: /usr/local/go/src/runtime/proc.go:250 runtime.main()
Apr 06 20:13:28  zkevm-node[30287]:         {"pid": 30287, "version": "v0.0.3-RC36"}
Apr 06 20:13:28  zkevm-node[30287]: main.start
Apr 06 20:13:28  zkevm-node[30287]:         /tmp/zkevmnode-0.0.3-RC36/cmd/run.go:98
Apr 06 20:13:28  zkevm-node[30287]: github.com/urfave/cli/v2.(*Command).Run
Apr 06 20:13:28  zkevm-node[30287]:         /home/ansible-10000/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274
Apr 06 20:13:28  zkevm-node[30287]: github.com/urfave/cli/v2.(*Command).Run
Apr 06 20:13:28  zkevm-node[30287]:         /home/ansible-10000/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:267
Apr 06 20:13:28  zkevm-node[30287]: github.com/urfave/cli/v2.(*App).RunContext
Apr 06 20:13:28  zkevm-node[30287]:         /home/ansible-10000/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332
Apr 06 20:13:28  zkevm-node[30287]: github.com/urfave/cli/v2.(*App).Run
Apr 06 20:13:28  zkevm-node[30287]:         /home/ansible-10000/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309
Apr 06 20:13:28  zkevm-node[30287]: main.main
Apr 06 20:13:28  zkevm-node[30287]:         /tmp/zkevmnode-0.0.3-RC36/cmd/main.go:140
Apr 06 20:13:28  zkevm-node[30287]: runtime.main
Apr 06 20:13:28  zkevm-node[30287]:         /usr/local/go/src/runtime/proc.go:250
Apr 06 20:13:28  systemd[1]: zksync.service: Main process exited, code=exited, status=1/FAILURE
````

**Comment by kompotkot** [comment]
Same, for node with Geth and Lighthouse, `zkevm-rpc` returns an error `FATAL   cmd/run.go:98   error getting forks: request timed out`

**Comment by arnaubennassar** [comment]
can you guys share your config? This step tries to fetch some data from a smart contract, if you don't have the correct addresses for the network this could happen

**Comment by arnaubennassar** [comment]
#1953 should be fixed using `v0.0.6` for the node

**Comment by ARR552** [comment]
Hello, the problem is not in the zkevm-node. It is a configuration problem in the geth node you are using. By default the `ReadTimeout` is 30s. Depending on the resources of the machine that it is running the geth, the query can be faster or slower. 
To fix this problem you should update the configuration file of your geth node. This is the section that should be affected.

```
[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
```
I've created this PR with a modification to minimize the impact of the wrong config in geth
https://github.com/0xPolygonHermez/zkevm-node/pull/2076

**Comment by bimlas** [comment]
@ARR552 Thanks for the tip, I modified `ReadTimeout = 30000000000` to `90000000000`, but the issue still exists. Waiting for the release contains your PR.

**Comment by bimlas** [comment]
I've tried to do the same in a separate script as `GetForks` method does, but it would take a lot of minutes to execute. Is this intended to run fast?

```javascript
  console.log('Getting PolygonZK forks', await connection.getLogs({
    fromBlock: 1,
    // Works if I specify a simple block:
    // fromBlock: 16896721, 
    // toBlock: 16896722,
    addresses: ["0x5132A183E9F3CB7C848b0AAC5Ae0c4f0491B7aB2" /* PoEAddr */, "0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb" /* GlobalExitRootManagerAddr */ ],
    topics: ["0xed7be53c9f1a96a481223b15568a5b1a475e01a74b347d6ca187c8bf0c078cd6" /* UpdateZkEVMVersion */]
  }));
```

This is where the timeout error dropped:

http://github.com/0xPolygonHermez/zkevm-node/blob/release/v0.0.8/etherman/etherman.go#L215-L225

**Comment by d10r** [comment]
> I've tried out the same code on an Alchemy enpoint, I've got the answer less then a second. What could be wrong with my RPC? What are the recommended setting to tweak getLogs()?

very likely Alchemy uses some caching layer which allows such fast responses for recurring requests.

I also had the issue, with a decent server, default geth config (30s timeout).

Since this issue keeps popping up, it may be a good idea to reduce the query log range used by zksync client.
