### ISSUE TITLE
The node data is inconsistent with the official rpc.

### ISSUE THREAD

**Issue by masayil** [0xPolygonHermez/zkevm-node#2162]
#### System information

zkEVM Node version: `v0.0.8`
zkEVM prover version: `hermeznetwork/zkevm-prover:c231382`
OS & Version: `Ubuntu20.04`
Commit hash : (if `develop`)
Network: `Mainnet`
I started a mainnet node at local.But the node data is inconsistent with the official rpc.
```
curl -X POST -H 'content-type:application/json' -d '{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0x105","toBlock":"0x105"}]}'  http://127.0.0.1:4050
{"jsonrpc":"2.0","id":1,"result":[{"address":"0x1e4a5963abfd975d8c9021ce480b42188849d41d","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000005a995fa324e9281493007375bd6e03a6dadcf4bd"],"data":"0x00000000000000000000000000000000000000000000000000000004a7817c9c","blockNumber":"0x105","transactionHash":"0x53688aadda53050a0ce8a80af92f3d788cdee762fe00c45ef2dc5e31e62943b8","transactionIndex":"0x0","blockHash":"0xc875b101d29c4285d4cad62098fd47ff406f290d69ade55efca62877f64ab446","logIndex":"0x2","removed":false},{"address":"0x2a3dd3eb832af982ec71669e178424b10dca2ede","topics":["0x25308c93ceeed162da955b3f7ce3e3f93606579e40fb92029faa9efe27545983"],"data":"0x00000000000000000000000000000000000000000000000000000000000000540000000000000000000000000000000000000000000000000000000000000000000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec70000000000000000000000005a995fa324e9281493007375bd6e03a6dadcf4bd00000000000000000000000000000000000000000000000000000004a7817c9c","blockNumber":"0x105","transactionHash":"0x53688aadda53050a0ce8a80af92f3d788cdee762fe00c45ef2dc5e31e62943b8","transactionIndex":"0x0","blockHash":"0xc875b101d29c4285d4cad62098fd47ff406f290d69ade55efca62877f64ab446","logIndex":"0x3","removed":false}]}
```

**Comment by masayil** [comment]
my node setting:
[polygon-zkevm.zip](https://github.com/0xPolygonHermez/zkevm-node/files/11644662/polygon-zkevm.zip)

**Comment by masayil** [comment]
@ARR552

**Comment by masayil** [comment]
The logIndex of the query result is different.This seems to be caused by a different collation. The LogIndex of the third-party rpc is dependent on Batch.
[Block 0x105](https://zkevm.polygonscan.com/txs?batch=73)It is the third block in the batch and has a log in the first and second blocks.

**Comment by masayil** [comment]
I found a  example in the testnet scan.https://testnet-zkevm.polygonscan.com/txs?batch=8939.

**Comment by masayil** [comment]
In addition, in the latest block, the blockhash and parenthash returned by the third-party RPC are also different from the official RPC. This is the same issue as #2106

**Comment by tclemos** [comment]
@masayil please, update your `Node` and `Prover/Executor` to the latest version as described here: https://github.com/0xPolygonHermez

The log index and wrong block hash generation are already fixed on it.

This will require a full resync in order to fix the data.

**Comment by ideal93** [comment]
Hi, @tclemos.  I'm trying to use the latest version of Node and Prover/Executor to resync all data, And I found that the 'wrong block hash' issue still hasn't been resolved. 

The generated hash of block 831 is always consistent with the third-party RPC. 
```
block_hash:  0x2589dcc6781e13317d8e128bc3bb4f90a0e0be0effa6f86c4bc4a3a7f0863eef. 
```
![image](https://github.com/0xPolygonHermez/zkevm-node/assets/12667721/8a781d4f-9a6b-4255-8810-96fa0e1db7a0)
Here is my operating procedure.
```
mkdir zkevm-node
cd zkevm-node
mkdir config

ZKEVM_DIR=./zkevm
ZKEVM_CONFIG_DIR=./config/
ZKEVM_ADVANCED_CONFIG_DI=./config/
ZKEVM_NET=mainnet

curl -L https://github.com/0xPolygonHermez/zkevm-node/releases/latest/download/$ZKEVM_NET.zip > $ZKEVM_NET.zip && unzip -o $ZKEVM_NET.zip -d $ZKEVM_DIR && rm $ZKEVM_NET.zip
cp $ZKEVM_DIR/$ZKEVM_NET/example.env $ZKEVM_CONFIG_DIR/.env

# EDIT THIS env file:
nano $ZKEVM_CONFIG_DIR/.env

sudo docker-compose --env-file $ZKEVM_CONFIG_DIR/.env -f $ZKEVM_DIR/$ZKEVM_NET/docker-compose.yml up
```
